spring.application.name=attendance

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d8cor457vvec73bb0720-a.oregon-postgres.render.com:5432/attendance_db_u9m7
spring.datasource.username=attendance_db_u9m7_user
spring.datasource.password=bEnDloEu2o3QaGin8Tg18EA7c85t0fOB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:9s8d7f6g5h4j3k2l1m0qwertyuiopASDFGHJKLZXCVBNM}
app.jwt.expiration-minutes=${JWT_EXP_MINUTES:480}

# Bootstrap Admin User
app.bootstrap.admin.username=${BOOTSTRAP_ADMIN_USERNAME}
app.bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD}

# Odoo integration (scaffold)
odoo.enabled=${ODOO_ENABLED:false}
odoo.base-url=${ODOO_BASE_URL:}
odoo.db=${ODOO_DB:}
odoo.username=${ODOO_USERNAME:}
odoo.password=${ODOO_PASSWORD:}